# TV HASS Module
#
# Provides automation for TV

media_player:

  - platform: lg_netcast
    #name: tvlg
    host: 192.168.0.31
    access_token: !secret mediaplayer_tvlg

automation:

  - alias: Stop Music on TV
    trigger:
      - platform: state
        entity_id: media_player.lg_tv_remote
        to: 'playing'
    action:
      - service: media_player.media_pause
        entity_id:
          - media_player.clementine_remote

script:

  dev_tv_turn_on:
    sequence:
      #- service: hdmi_cec.select_device
      #  data:
      #    device: TV
      - service: hdmi_cec.power_on
        data:
          device: TV
